[env:waveshare_lcd_4_3]
platform = espressif32
board = esp32-s3-devkitc-1
#framework = arduino
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
framework = espidf
upload_speed=921600
monitor_speed=115200
monitor_filters = esp32_exception_decoder
lib_ldf_mode = deep
lib_deps = lvgl/lvgl@9.4
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
build_flags = -std=gnu++17
    -DCORE_DEBUG_LEVEL=5
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
    -DCONFIG_SOC_CPU_HAS_FPU=1
    -DBOARD_HAS_PSRAM
	-DWAVESHARE_LCD_4_3INCH
    -DLV_CONF_INCLUDE_SIMPLE
	-Iinclude
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_CDC_ON_BOOT=1
#upload_port = COM10
#monitor_port = COM10